config/routes.rb
Rails.application.routes.draw do
  get 'retrieve_files/index'

  get 'retrieve_files/show'

  resources :rsvp, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'main/index'

  root :to => "main#index"
  get "when_where" => "when_where#index"
  get "gallery" => 'gallery#index'
end

app/models/imagetool.rb
#require 'dragonfly'
require 'fileutils'

class  ImageTools
  #include Magick

  aspect_ratio = 0.75

  # You can leave +height+ blank if you like.
  def self.thumb_path(blob, w, h)
    "/images/thumbs/#{blob}/#{w.to_i}x#{h.to_i}.jpg"
  end

  # Where to store images in the filesystem when they
  # are created.
  def self.image_path(blob, w, h = nil)
    "#{RAILS_ROOT}/public#{thumb_path(blob, w, h)}"
  end

  def self.create_blob_client
    # Setup a specific instance of an Azure::Storage::Blob::BlobService
    blob_client = Azure::Storage::Blob::BlobService.create(storage_account_name: 'deefredstorage', storage_access_key: 'DbY0ZInVLLD+GcXXZwZCntkBNdtkRp0gxhHYRPQVHnqgVwDKnebUIwSMpQ5B0R9/S420Xs0u1AeV7bPXuDxZ2Q==')
    return blob_client
  end

  def self.get_url(blob_name)
    url = "https://deefredstorage.blob.core.windows.net/deefred/"+blob_name
    return url
  end

  def self.get_blob_properties(blob)
    client = create_blob_client
    blob, content = client.get_blob_properties("deefred", blob)::File.open('download.png', 'wb') {|f| f.write(content)}
    return content
  end

  def self.list_blobs
    client = create_blob_client
    return client.list_blobs("deefred")
  end

  def self.get_blob(blob_name)
    client = create_blob_client
    blob, content = client.get_blob("deefred", blob_name)::File.open('download.png', 'wb') {|f| f.write(content)}
    return content
  end

  # def thumbnail(blob_name, width, height = nil)
  #   blob_content = get_blob(blob_name)
  #   return nil unless blob_content

  #   target = image_path(blob_name, with, height)

  #   height ||= width

  #   img = Image.read(source).first
  #   rows, cols = img.rows, img.columns

  #   source_aspect = cols.to_f / rows
  #   target_aspect = width.to_f / height
  #   thumbnail_wider = target_aspect > source_aspect

  #   factor = thumbnail_wider ? width.to_f / cols : height.to_f / rows
  #   img.thumbnail!(factor)
  #   img.crop!(CenterGravity, width, height)

  #   FileUtils.mkdir_p(File.dirname(target))
  #   img.write(target) { self.quality = 75 }
  # end

end

app/models/rsvp.rb
class Rsvp
  include Mongoid::Document

  field :name, type: String
  field :email, type: String

  validates_presence_of :name
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_message, :set_rsvp
  def set_message
    @message = flash[:message]
  end

  def set_rsvp
    @rsvp = Rsvp.new
  end

end

app/controllers/gallery_controller.rb
require File.join(Rails.root, 'app', 'models', 'imagetool.rb')

class GalleryController < ApplicationController
  def index
    @blobs = []
    blobs = ImageTools.list_blobs
    for blob in blobs do
      @blobs.push ImageTools.get_url(blob.name)
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def gallery
  end

  def when_where
  end
end

app/controllers/retrieve_files_controller.rb
class RetrieveFilesController < ApplicationController

  def index
    
  end

  def show
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def create
    @rsvp = Rsvp.create(save_params)
    if @rsvp.save
      flash[:message] = "Sua presença foi registrada com sucesso. Obrigado!"
    else
      flash[:message] = "Não foi possível registrar sua presença, por favor tente novamente"
    end
    redirect_back fallback_location: root_path
  end


  private
    # Using a private method to encapsulate the permissible parameters
    # is just a good pattern since you'll be able to reuse the same
    # permit list between create and update. Also, you can specialize
    # this method with per-user checking of permissible attributes.
    def save_params
      params.require(:rsvp).permit(:name, :email)
    end

end

app/controllers/when_where_controller.rb
class WhenWhereController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/retrieve_files_helper.rb
module RetrieveFilesHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/when_where_helper.rb
module WhenWhereHelper
end

app/views/gallery/index.html.erb
<% content_for :pre_menu do %>
<% end %>
<div id="fh5co-gallery">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
                <h2>Videos</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="gallery animate-box">
                    <a class="gallery-img popup-youtube" href="http://www.youtube.com/watch?v=u8OgHO6VE-I">
                        <img src="https://img.youtube.com/vi/u8OgHO6VE-I/0.jpg" class="img-responsive" alt="Video Dança" />
                    </a>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="gallery animate-box">
                    <a class="gallery-img popup-youtube" href="http://www.youtube.com/watch?v=65eHIbyka-Q">
                        <img src="https://img.youtube.com/vi/65eHIbyka-Q/0.jpg" class="img-responsive" alt="Video Cabo Frio" />
                    </a>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-gallery">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
                <h2>Fotos</h2>
            </div>
        </div>
        <div class="row">
            <%for blob in @blobs do%>
            <div class="col-sm-4">
                <div class="gallery animate-box">
                    <a class="gallery-img image-popup image-popup" href="<%=blob%>">
                        <img src="<%=blob%>" class="img-responsive" alt="Image" />
                    </a>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</div>

<%= render "shared/rsvp" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Casamento Dê e Fred - <%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Casamento De e Fred" />
    <meta name="keywords" content="casamento, fred, de, love" />
    <meta name="author" content="Fred" />

    <!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FREEHTML5.CO
		
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Montez" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="css/superfish.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">

    <link rel="stylesheet" href="css/style.css">


    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
</head>

<body>
    <div id="fh5co-wrapper">
        <div id="fh5co-page">
          <%if @message != nil && @mesage != ""%>
              <div class="alert alert-warning" role="alert">
                <%=@message%>
              </div>
          <%end%>
          <%= yield :pre_menu %>
          <%= render "shared/menu" %>
          <%= yield %>
          <%= render "shared/footer" %>
        </div>
        <!-- END fh5co-page -->

    </div>
    <!-- END fh5co-wrapper -->

    <!-- Google Map -->
    
    <!-- jQuery -->
    <script src="dist/scripts.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>

</html>

app/views/main/groom-bride.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Casamento De e Fred</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Casamento De e Fred" />
    <meta name="keywords" content="casamento, fred, de, love" />
    <meta name="author" content="Fred" />

    <!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FREEHTML5.CO
		
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Montez" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="css/superfish.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">

    <link rel="stylesheet" href="css/style.css">


    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>

<body>
    <div id="fh5co-wrapper">
        <div id="fh5co-page">

            <div class="fh5co-hero" data-section="home">
                <div class="fh5co-overlay"></div>
                <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url(images/cover_bg_1.jpg);">
                    <div class="display-t">
                        <div class="display-tc">
                            <div class="container">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="animate-box">
                                        <h1>Casamento Dê &amp; Fred</h1>
                                        <h2>O Noivo &amp; A Noiva</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <header id="fh5co-header-section" class="sticky-banner">
                <div class="container">
                    <div class="nav-header">
                        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                        <h1 id="fh5co-logo"><a href="index.html">O Casamento</a></h1>
                        <!-- START #fh5co-menu-wrap -->
                        <nav id="fh5co-menu-wrap" role="navigation">
                            <ul class="sf-menu" id="fh5co-primary-menu">
                                <li><a href="index.html">O Casamento</a></li>
                                <li class="active"><a href="groom-bride.html" class="fh5co-sub-ddown">O Noivo &amp; A Noiva</a></li>
                                <li><a href="when-where.html">Quando &amp; Onde</a></li>
                                <li><a href="guest.html">Convidado</a></li>
                                <li><a href="gallery.html">Fotos</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>

            <!-- end:header-top -->


            <div id="fh5co-groom-bride">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
                            <h2>Noivo &amp; Noiva</h2>
                        </div>
                    </div>
                    <div class="row padding">
                        <div class="couple-wrap">
                            <div class="col-md-6 nopadding animate-box">
                                <img src="images/groom.jpg" class="img-responsive" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
                            </div>
                            <div class="col-md-6 nopadding animate-box">
                                <div class="couple-desc">
                                    <h3>Fred</h3>
                                    <p>Inteligente, esperto, bonito e humilde, é o fiel ajudante da exuberante noiva, e busca junto a ela sobreviver aos grandes desafios da vida a dois.</p>
                                    <p class="fh5co-social-icons">
                                        <a href="#"><i class="icon-twitter2"></i></a>
                                        <a href="#"><i class="icon-facebook2"></i></a>
                                        <a href="#"><i class="icon-instagram"></i></a>
                                        <a href="#"><i class="icon-dribbble2"></i></a>
                                        <a href="#"><i class="icon-youtube"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row padding">
                        <div class="couple-wrap">
                            <div class="col-md-6 col-md-push-6 nopadding animate-box">
                                <img src="images/bride.jpg" class="img-responsive" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
                            </div>
                            <div class="col-md-6 col-md-pull-6 nopadding animate-box">
                                <div class="couple-desc">
                                    <h3>Dê</h3>
                                    <p>Linda, exuberante, espetacular e exagerada é a cabeça da equipe. Junto de seu incansável companheiro (desde que sejam antes das 22), combate diariamente as vilânias da pia suja, das contas a pagar e das pequenas limpezas
                                        diárias.
                                    </p>
                                    <p class="fh5co-social-icons">
                                        <a href="#"><i class="icon-twitter2"></i></a>
                                        <a href="#"><i class="icon-facebook2"></i></a>
                                        <a href="#"><i class="icon-instagram"></i></a>
                                        <a href="#"><i class="icon-dribbble2"></i></a>
                                        <a href="#"><i class="icon-youtube"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div id="fh5co-started" style="background-image:url(images/cover_bg_2.jpg);" data-stellar-background-ratio="0.5">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row animate-box">
                        <div class="col-md-8 col-md-offset-2 text-center heading-section">
                            <h2>RSVP</h2>
                            <p>Por favor preencha o formulário abaixo informando se poderá comparecer. Obrigado!
                        </div>
                    </div>
                    <div class="row animate-box">
                        <div class="col-md-10 col-md-offset-1">
                            <form class="form-inline">
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        <label for="name" class="sr-only">Nome</label>
                                        <input type="name" class="form-control" id="name" placeholder="Name">
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        <label for="email" class="sr-only">E-mail</label>
                                        <input type="email" class="form-control" id="email" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4">
                                    <button type="submit" class="btn btn-primary btn-block">Irei comparecer</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <footer>
                <div id="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <h2>Dê &amp; Fred</h2>
                            </div>
                            <div class="col-md-6 col-md-offset-3 text-center">
                                <p class="fh5co-social-icons">
                                    <a href="#"><i class="icon-twitter2"></i></a>
                                    <a href="#"><i class="icon-facebook2"></i></a>
                                    <a href="#"><i class="icon-instagram"></i></a>
                                    <a href="#"><i class="icon-dribbble2"></i></a>
                                    <a href="#"><i class="icon-youtube"></i></a>
                                </p>
                                <p>Copyright 2016 Free Html5 <a href="#">Module</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a>></p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>



        </div>
        <!-- END fh5co-page -->

    </div>
    <!-- END fh5co-wrapper -->

    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCefOgb1ZWqYtj7raVSmN4PL2WkTrc-KyA&sensor=false"></script>
    <!-- jQuery -->
    <script src="dist/scripts.min.js"></script>
</body>

</html>

app/views/main/index.html.erb
<% content_for :pre_menu do %>
<div class="fh5co-hero" data-section="home">
    <div class="fh5co-overlay"></div>
    <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url(images/cover_bg_1.jpg);">
        <div class="display-t">
            <div class="display-tc">
                <div class="container">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="animate-box">
                            <h1>O casamento</h1>
                            <h2>Dê &amp; Fred</h2>
                            <p><span>08.04.2018</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

<div id="fh5co-couple" class="fh5co-section-gray">
    <div class="container">
        <div class="row row-bottom-padded-md animate-box">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="col-md-5 col-sm-5 col-xs-5 nopadding">
                    <img src="https://deefredstorage.blob.core.windows.net/deefred-outras/foto_fred.jpg" class="img-responsive" alt="Fred">
                    <h3>Fred</h3>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-2 nopadding">
                    <h2 class="amp-center"><i class="icon-heart"></i></h2>
                </div>
                <div class="col-md-5 col-sm-5 col-xs-5 nopadding">
                    <img src="https://deefredstorage.blob.core.windows.net/deefred-outras/foto_de.jpg" class="img-responsive" alt="Dê">
                    <h3>Dê</h3>
                </div>
            </div>
        </div>
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2">
                <div class="col-md-12 text-center heading-section">
                    <h2>Estão casando</h2>
                    <p><strong>em 08 de abril de 2018 &mdash; Belo Horizonte, Minas Gerais</strong></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-countdown">
    <div class="row">
        <div id="demo" class="col-md-8 col-md-offset-2 text-center animate-box">
            <p class="countdown">
                <span id="days"></span>
                <span id="hours"></span>
                <span id="minutes"></span>
                <span id="seconds"></span>
            </p>
        </div>
    </div>
</div>

<%= render "shared/rsvp" %>

app/views/retrieve_files/index.html.erb
<h1>RetrieveFiles#index</h1>
<p>Find me in app/views/retrieve_files/index.html.erb</p>

app/views/retrieve_files/show.html.erb
<h1>RetrieveFiles#show</h1>
<p>Find me in app/views/retrieve_files/show.html.erb</p>

app/views/rsvp/create.html.erb
<h1>Rsvp#create</h1>
<p>Find me in app/views/rsvp/create.html.erb</p>

app/views/rsvp/show.html.erb
<h1>Rsvp#show</h1>
<p>Find me in app/views/rsvp/show.html.erb</p>

app/views/shared/_footer.html.erb
<footer>
    <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2>Dê &amp; Fred</h2>
                </div>
                <div class="col-md-6 col-md-offset-3 text-center">
                    <p class="fh5co-social-icons">
                        <a href="#"><i class="icon-twitter2"></i></a>
                        <a href="#"><i class="icon-facebook2"></i></a>
                        <a href="#"><i class="icon-instagram"></i></a>
                        <a href="#"><i class="icon-dribbble2"></i></a>
                        <a href="#"><i class="icon-youtube"></i></a>
                    </p>
                    <p>Copyright 2016 Free Html5 <a href="#">Module</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a>></p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_menu.html.erb
<header id="fh5co-header-section" class="sticky-banner">
    <div class="container">
        <div class="nav-header">
            <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
            <h1 id="fh5co-logo"><%=link_to "Casamento", root_path%></h1>
            <!-- START #fh5co-menu-wrap -->
            <nav id="fh5co-menu-wrap" role="navigation">
                <ul class="sf-menu" id="fh5co-primary-menu">
                    <li class="active"><%=link_to "O Casamento", root_path%></li>
                    <!--<li><a href="groom-bride.html" class="fh5co-sub-ddown">Noivo &amp; Noiva</a></li>-->
                    <li><%=link_to "Onde", when_where_path%></li>
                    <li><%=link_to "Fotos e Videos", gallery_path%></li>
                    <li><%=link_to "Lista de Presentes - LaVille", "http://www.lavillecasa.com.br/list/B058354"%></li>
                    <li><%=link_to "Lista de Presentes", "https://deefred.zankyou.com"%></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/shared/_rsvp.html.erb
<div id="fh5co-started" style="background-image:url(images/cover_bg_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center heading-section">
                <h2>RSVP</h2>
                <p>Por favor preencha o formulário abaixo informando se poderá comparecer. Obrigado!
            </div>
        </div>
        <div class="row animate-box">
                <div class="col-md-10 col-md-offset-1">
                    <%= form_for @rsvp, url: rsvp_index_path, html: {class: "form-inline"} do |f| %>
                    <div class="col-md-4 col-sm-4">
                        <div class="form-group">
                            <%=label_tag 'name', 'Nome', class: "sr-only"%>
                            <%= f.text_field :name, type:"name", class: "form_control", placeholder: "Name" %>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                            <div class="form-group">
                                <%=label_tag 'email', 'E-mail', class: "sr-only"%>
                                <%= f.text_field :email, type:"email", class: "form_control", placeholder: "Email" %>
                            </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <%= f.submit "Irei comparecer", class: "btn btn-primary btn-block" %>
                    </div>
                    <% end %>
                </div>
            </div>
    </div>
</div>

app/views/when_where/index.html.erb
<div id="fh5co-when-where" class="fh5co-section-gray">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
                <h2>Onde &amp; Quando</h2>
            </div>
        </div>
        <div class="row row-bottom-padded-md">
            <div class="col-md-12 text-center animate-box">
                <div class="wedding-events">
                    <div class="ceremony-bg" style="background-image: url(https://deefredstorage.blob.core.windows.net/deefred-outras/Colonial.jpg);"></div>
                    <div class="desc">
                        <h3>Cerimônia e Celebraç&atilde;o</h3>
                        <p><strong>Domingo, 08 de abril de 2018, 16:30 - Belo Horizonte / MG</strong></p>
                        <p>Em um lindo casarão colonial localizado na orla da pampulha, localizado na Avenida Otácilio Negr&atilde;o de lima, n˚ 16200</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="fh5co-map">
                    <iframe width="100%" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/search?q=Avenida%20Ot%C3%A1cilio%20Negr%C3%A3o%20de%20lima%2C%20n%CB%9A%2016200%2C%20Belo%20Horizonte%2C%20MG&key=AIzaSyA9X2xZY2HKeuQ4sSXrmWS19Af_yC22eVU" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
    
    <%= render "shared/rsvp" %>